### ISSUE TITLE
first user story - query settings

### ISSUE THREAD

**Issue by WalterRestifo** [WalterRestifo/user-stories#1]
## Value Proposition

**As a** user

**I need** to decide what kind of people I wanna match

**to be able to** choose how my teammates should be like

## Description
<img width="456" alt="Bildschirmfoto 2022-12-09 um 14 20 37" src="https://user-images.githubusercontent.com/116001970/206711577-dd76f0ab-fd8c-4433-965c-2dbf0cda71e4.png">

## Acceptance Criteria

- [ ] three dropdown menus
- [ ] menu skill has options A+, A,B,C,D  and beginners
- [ ] menu Language has German, English , Spanish and none
- [ ] menu Gender has Male, Female, Diverse and Not relevant
- [ ] chosen criteria are saved in a variable after submit
- [ ] a submit button with the text "search for buddies"

## Tasks

- [ ] Make a header
- [ ] make three drop down menus with the same layout like in the description
- [ ] save the chosen criteria in a variable when submitted

**Comment by ufelgen** [comment]
Hey Walter, ich würde für das gender dropdown menu auch eine Option "mir egal" einbauen :) Und wenn das dein Einstieg in die App wird, also das allererste das du programmierst, hat denn der User danach auch ein funktionierendes Produkt? kann er/sie was damit anfangen, bei den 3 dropdown menus was auswählen kann?

**Comment by WalterRestifo** [comment]
Ja, du hast Recht, das mit der "mir Egal" Option hatte ich vor, aber habe es dann doch vergessen. Ich fixe es gleich, vielen Dank. Was das fertige Produkt angeht, man kann nicht in der allerersten Userstory eine Fertige App haben. Ich finde, eine funktionierende Auswahlfunktion die die Kriterien in eine Variable gespeichert wird, in sich schon eine Userstory entspricht. Aber vielleicht irre ich mich. Mal sehen was die Coaches sagen.
