### ISSUE TITLE
simple matching algorithm

### ISSUE THREAD

**Issue by WalterRestifo** [WalterRestifo/user-stories#2]
## Value Proposition

**As a** user

**I need** see people that match my criteria

**to be able to** see who can I play with

## Description
<img width="391" alt="Bildschirmfoto 2022-12-09 um 14 36 40" src="https://user-images.githubusercontent.com/116001970/206714376-a15ef5f3-6746-4572-9b6d-f61a0c38a40e.png">

## Acceptance Criteria

- [ ] the algorithm should filter the array with all the data of the players 
- [ ] the algorithm should return a new array with the data of only the players with the chosen criteria
- [ ] the array with the data of all the players must remain unchanged
- [ ] the name of the objects in the new array should be rendered in cards with a passable layout

## Tasks

- [ ] make an array with dummy data of players
- [ ] make a dummy variable with Criteria of some kind
- [ ] make a new array with only the data of the players with the Criteria of the variable
- [ ] render the new array in cards
