### ISSUE TITLE
records of the game

### ISSUE THREAD

**Issue by WalterRestifo** [WalterRestifo/user-stories#4]
## Value Proposition

**As a** user

**I need** to record the final point score of a game

**to be able to** show friends, how many games I win

## Description

Scribble / design or text

## Acceptance Criteria

- [ ] new page called games
- [ ] a 
- [ ] ...

## Tasks

(for developers team)

- [ ] list the tasks that need to be performend within the dev team
- [ ] e.g. Components, Storybook, testing
- [ ] ...
