### ISSUE TITLE
first user story - render the cards

### ISSUE THREAD

**Issue by WalterRestifo** [WalterRestifo/user-stories#5]
## Value Proposition

**As a** user

**I need** to see the cards of the players

**to be able to** look who can I play with

## Description

<img width="519" alt="Bildschirmfoto 2022-12-12 um 09 57 14" src="https://user-images.githubusercontent.com/116001970/207003311-c407e286-019f-47f6-a497-63bd544f698e.png">

## Acceptance Criteria

- [ ]  an array with dummy data for the players
- [ ] the data are rendered in cards
- [ ] an Header with the name of the App "MatchBall"

## Tasks

(for developers team)

- [ ] create an array with dummy data for the players
- [ ] map on the array and put the data in a card component
- [ ] write the header

**Comment by julialoeschel** [comment]
great. 
simple - on point. 
easy to understand. 

maybe we can think of: 
- is the list scollable?
- what happens with very long names
- ...

:octocat:
