### ISSUE TITLE
US2 matching 

### ISSUE THREAD

**Issue by WalterRestifo** [WalterRestifo/user-stories#6]
## Value Proposition

**As a** user

**I need** to set criteria for the search

**to be able to** only see the players I can imagine to play with

## Description

<img width="506" alt="Bildschirmfoto 2022-12-09 um 15 44 42" src="https://user-images.githubusercontent.com/116001970/206727562-f4fcd87e-187b-4831-a032-dadf5957e218.png">

## Acceptance Criteria
- [ ] three dropdown menus
- [ ] menu skill has options A+, A,B,C,D  and beginners
- [ ] menu Language has German, English , Spanish and Not relevant
- [ ] menu Gender has Male, Female, Diverse and Not relevant
- [ ] chosen criteria are saved in a variable after submit
- [ ] a submit button with the text "search for buddies"
- [ ]  the algorithm should filter the array with all the data of the players 
- [ ] the algorithm should return a new array with the data of only the players with the chosen criteria
- [ ] the array with the data of all the players must remain unchanged
- [ ] the name of the objects in the new array should be rendered in cards with a passable layout

## Tasks

(for developers team)

- [ ] make three drop down menus with the same layout like in the description
- [ ] save the chosen criteria in a variable when submitted
- [ ] make a new array with only the data of the players with the Criteria of the variable
- [ ] render the new array in cards
